### PR TITLE
[WIP] Upgrade to React 16

### PR DESCRIPTION
**Pull request by garbles**
I am dumb. Not sure what I'm missing but specs are failing.

### CODE REVIEW

**Comment by ezmiller** [comment]
How is this going? I need this too.

**Comment by garbles** [comment]
@ezmiller haven't had any chance to follow up on this. If you're so inclined, you can check out this branch and create a new PR with whatever fix it requires. 😄

**Comment by ezmiller** [comment]
I will see if I can get to it. What were the problems that you encountered? Do you recall?

**Comment by garbles** [comment]
Just failing tests. I'm going to upgrade the dependency to `16.1.0` to see whether that changes anything.

**Comment by garbles** [comment]
Did a prerelease. Install with `yarn add flag@3.0.0-0`

**Pull request merged**
