### PR TITLE
add replace flags action

### PR DESCRIPTION
**Pull request by npgm**
Allows for flag state to be replaced

### CODE REVIEW

**Comment by garbles** [comment]
Hi @npgm,

The flag state can already be replaced by passing new values for all flags to `setFlagsAction`.

But anyway, what does unsetting a flag to `undefined` afford you? It's much safer to explicitly set it to `undefined` in `setFlagsAction`, where the type of the value would be `A | void` (where `A` is generic).

Also, I think you might be missing a file or two in this commit.

**Comment by npgm** [comment]
> Also, I think you might be missing a file or two in this commit.

fixed! 

> The flag state can already be replaced by passing new values for all flags to setFlagsAction.

In our system the set of feature flags is not defined statically, its whatever is in the database. Because of this enumerating flags when we need to unset all flags is tedious.

**Comment by garbles** [comment]
Can you provide an example of how the flags might change from page to page?

**Comment by npgm** [comment]
Present state: Feature flags are per company in our app. Users belong to a
single company.

Desired state: A user can be associated with multiple companies and switch
between companies in the app. Switching companies should load the exact set
of feature flags for that company.

**Comment by garbles** [comment]
Cool thanks. If I run `yarn build` on this branch I get errors. Turned on TravisCI for the project, so I hope pull requests will get checked for you.

**Comment by npgm** [comment]
> Cool thanks. If I run yarn build on this branch I get errors. Turned on TravisCI for the project, so I hope pull requests will get checked for you.

Looks like you might need to add a travis config file

Things should be good now: 

```
$ yarn test
yarn test v1.0.2
$ jest
 PASS  src/index.test.tsx
  createFlagsReducer
    ✓ creates a reducer function for flags (3ms)
    ✓ sets flags when the correct flag is dispatched (1ms)
    ✓ replaces flags when the correct flag is dispatched (1ms)
  FlagsProvider && Flag
    ✓ accepts uncomputed flags as props (18ms)
    ✓ passes flags and other props to the render function (1ms)
    ✓ can render with a component (1ms)
    ✓ can fallback to a component (1ms)
    ✓ can render children if they are provided present and flag is truthy (2ms)
    ✓ can render nothing if children are provided but flags are falsy
  ConnectedFlagsProvider && Flag
    ✓ fetches flag values off of state (10ms)
    ✓ renders falsy when the value does not exist (1ms)
  withFlags
    ✓ creates a higher order component by pulling them in (1ms)

Test Suites: 1 passed, 1 total
Tests:       12 passed, 12 total
Snapshots:   0 total
Time:        1.555s
Ran all test suites.
✨  Done in 2.30s.
$ yarn build
yarn build v1.0.2
$ rm -rf build && tsc --outDir build -d
✨  Done in 2.52s.
$ 
```

**Comment by npgm** [comment]
Any updates @garbles?

**Comment by garbles** [comment]
@npgm hey sorry. haven't been able to take a look. i'll make a note to take a look tonight

**Comment by ltankey** [comment]
> But anyway, what does unsetting a flag to undefined afford you? It's much safer to explicitly set it to undefined in setFlagsAction, where the type of the value would be A | void (where A is generic).

I think I'm missing something, but if I set a feature to `undefined` in my `setFlagsAction`, the payload resolves to an empty object.

**Comment by garbles** [comment]
Sorry that I haven't been up to date on this. Rewrote this entire lib with strong TypeScript support, so changing the shape of the flags is not an option.

**Pull request closed without merging**
